services:
  api-sistema-ponto:
    build: .
    container_name: api-sistema-ponto
    restart: unless-stopped
    entrypoint: ./entrypoint.sh
    ports:
      - "5000:5000"
    volumes:
      - .:/app
